site_name: open_educational_ocean_recorder
repo_url: https://github.com/gheleguen/open_educational_ocean_recorder.git
edit_uri: -/edit/main/docs/

nav:
  - Introduction: index.md
  - I. Guide de fabrication:
    - A. Sourcer: 0-1-0_sourcer.md
    - B. Préparation des pièces: 0-1-0_productions_of_parts_fr.md
    - C. Guide d'assemblage: 0-1-0_guide_assemblage.md
    - D. Programmer la sonde: 0-1-0_guide_upload.md
    - Ax/ Annexes:
      - Tester le capteur de température: 0-0-1_test_temp-sensor.md
      - Tester l'horloge RTC: 0-0-1_test_set_rtc-ds3231.md
  - II. Guide d'utilisation: 0-1-0_user_guide.md
  - III. Contribuer : edit-this-doc_fr.md
  - Licence: license.md

theme:
    name: material
    palette:
      primary: blue

plugins:
  - search

markdown_extensions:
    - smarty
    - sane_lists
    - admonition
    - toc:
        permalink: true
