site_name: open_educational_ocean_recorder
repo_url: https://github.com/gheleguen/open_educational_ocean_recorder.git
edit_uri: -/edit/main/docs/

nav:
  - Introduction: index.md
  - I. Guide de fabrication:
    - 1/ Sourcer : 0-0-1_sourcer.md
    - 2/ Guide d'assemblage: 0-0-1_guide_assemblage.md
  - II. Guide d'utilisation: 0-0-1_user_guide.md
  - III. Contribuer : edit-this-doc_fr.md
  - Licence: license.md

theme:
    name: material
    palette:
      primary: blue

plugins:
  - search

markdown_extensions:
    - smarty
    - sane_lists
    - admonition
    - toc:
        permalink: true
